<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- REPORT GENERATOR -->
<!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),DF*,DS*,ES*,STA*,INP*,APP*,UPD*,NVD*,TNR*,FLG*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT DF (#PCDATA)>
<!ELEMENT DS (#PCDATA)>
<!ELEMENT ES (#PCDATA)>
<!ELEMENT STA (#PCDATA)>
<!ELEMENT INP (#PCDATA)>
<!ELEMENT APP (#PCDATA)>
<!ELEMENT UPD (#PCDATA)>
<!ELEMENT NVD (#PCDATA)>
<!ELEMENT TNR (#PCDATA)>
<!ELEMENT FLG (#PCDATA)>
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>1890 Institutions</DESCRIPTOR>
 <DF>Enacted August 30, 1890 (chapter 841, 26 Stat. 417), this
law authorized additional direct appropriations for the
land grant colleges of agriculture that had been
established under the Morrill Act of 1862.  The most
significant feature of the second Morrill Act was that the
1862 schools could receive the additional funds only if
they admitted blacks into their programs or if they
provided separate but equal agricultural higher education
to black students.</DF>
 <DS>Agriculture Glossary, House Committee on Agriculture,
United States House of Representatives.</DS>
 <ES>Instituciones de 1890</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>1994 Institutions</DESCRIPTOR>
 <DF>Native American tribally-controlled colleges and
universities that were granted land grant status under The
Elementary and Secondary Education Reauthorization Act of
1994.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Instituciones 1994</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>4-H Youth Development Program</DESCRIPTOR>
 <DF>The 4-H Youth Development Program is an international youth
outreach organization founded in 1902 to foster
agricultural, homemaking, leadership and other skills in
young people.  The 4-H name represents the ideals of the
program with its focus on Head, Heart, Hands and Health.
The program is administered by the United States Department
of Agriculture Cooperative Extension Service.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Programa de Desarrollo Juvenil 4-H</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>5&apos; untranslated regions</DESCRIPTOR>
 <DF>The sequence at the 5&apos; end of the messenger RNA
that does not code for product. This sequence
contains the ribosome binding site and other
transcription and translation regulating
sequences.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>regiones no traducidas 5&apos;</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>5-hydroxytryptophan</DESCRIPTOR>
 <DF>The immediate precursor in the biosynthesis of serotonin
from tryptophan. It is used as an antiepileptic and
antidepressant.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>5-hidroxitriptófano</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>A-DNA</DESCRIPTOR>
 <DF>The form of double-stranded DNA stable under
dehydrated conditions, found in crystals and
solutions with higher salt concentrations or
alcohol in the solute.  It has a more compact
helix than B-DNA with a deep, narrow major groove,
a wide, shallow minor groove, and a hollow center.
DNA:RNA complexes and double-stranded RNAs also
take this form.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>ADN-A</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abdominal fat</DESCRIPTOR>
 <DF>Body fat located in the abdominal region.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>grasa abdominal</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abnormal development</DESCRIPTOR>
 <DF>May be used for abnormal development in any
organism, which is characterized by the change in
the morphology of  anatomical structures.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>desarrollo anormal</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abortifacients</DESCRIPTOR>
 <DF>Chemical substances that interrupt pregnancy after
implantation.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>abortifacientes</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abortion (plants)</DESCRIPTOR>
 <DF>premature termination of the development of
pollen, gametes, embryos, seeds, fruits, flowers,
and etc.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>aborto (plantas)</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abscess</DESCRIPTOR>
 <DF>Accumulation of purulent material in tissues,
organs, or circumscribed spaces, usually
associated with signs of infection.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>abceso</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorbance</DESCRIPTOR>
 <DF>A measure of the amount of light absorbed by a
solution.  It is measured by a colorimeter or
spectrophotometer.   Absorbance values are used to
plot the growth of bacteria in suspension cultures
and to determine the concentration of molecules in
solution.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>absorbancia</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorbed dose</DESCRIPTOR>
 <DF>The amount of a substance penetrating across an absorption
barrier (the exchange boundaries) of an organism, via
either physical or biological processes.</DF>
 <DS>US Environmental Protection Agency</DS>
 <ES>dosis absorbida</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorbents</DESCRIPTOR>
 <DF>A substance that takes liquid in through the
surface and holds it.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>absorbentes</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorption</DESCRIPTOR>
 <DF>The taking in or incorporation of a substance.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>absorción</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorption barrier</DESCRIPTOR>
 <DF>Any surface that may retard the rate of penetration of a
biological, chemical, or physical agent into an organism.
Examples include the skin and the linings of the
respiratory and gastrointestinal tracts.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>barrera de absorción</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic achievement</DESCRIPTOR>
 <DF>Accomplishments relating to education, learning and study,
especially in schools and higher educational institutions.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>rendimiento académico</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acai berries</DESCRIPTOR>
 <DF>Small, round, purple fruits of the palm, Euterpe oleracea,
harvested for fruit, pulp or juice.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>acai berries</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accelerometry</DESCRIPTOR>
 <DF>Qualitative and quantitative measurement of movement
patterns.</DF>
 <DS>Medical Subject Headings 2013</DS>
 <ES>acelerometría</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acceptable daily intake</DESCRIPTOR>
 <DF>The amount of a substance to which an organism can be
exposed on a daily basis over an extended period of time
(usually a lifetime) without suffering deleterious effects.</DF>
 <DS>US Environmental Protection Agency</DS>
 <ES>ingesta diaria permitida</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acceptable risk</DESCRIPTOR>
 <DF>The level of risk that will be tolerated, depending on a
variety of social, economic, scientific and other factors
as well as any perceived benefits.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>riesgo aceptable</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Accipitridae</DESCRIPTOR>
 <DF>Family including eagles, hawks and kites.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Accipitridae</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accuracy</DESCRIPTOR>
 <DF>The extent to which a measurement approaches the
true value of the measured quantity.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>exactitud</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acer freemanii</DESCRIPTOR>
 <DF>Interspecific hybrid between Acer rubrum x Acer saccharinum.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Acer freemanii</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetaminophen</DESCRIPTOR>
 <DF>Analgesic antipyretic derivative of acetanilide.
It has weak anti-inflammatory properties and is
used as a common analgesic, but may cause liver,
blood cell, and kidney damage.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>acetaminofeno</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Achillea lewisii</DESCRIPTOR>
 <DF>Interspecific hybrid between Achillea clavennae x
Achillea tomentosa.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Achillea lewisii</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Achnatherum bloomeri</DESCRIPTOR>
 <DF>An interspecific hybrid of Achnatherum hymenoides x
Achnatherum occidentalis;  Also used for other hybrids
involving Achnatherum hymenoides.</DF>
 <DS>Germplasm Resources Information Network</DS>
 <ES>Achnatherum bloomeri</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Achnella</DESCRIPTOR>
 <DF>Intergeneric hybrid of Achnatherum x Nassella.</DF>
 <DS>Germplasm Resources Information Network</DS>
 <ES>Achnella</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid-base balance</DESCRIPTOR>
 <DF>The balance between acids and bases in the body fluids.
The pH (hydrogen-ion concentration) of the arterial blood
provides an index for the total body acid-base balance.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>balance ácido-base</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid soils</DESCRIPTOR>
 <DF>Soil with a pH less than 7.0.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>suelos ácidos</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid value</DESCRIPTOR>
 <DF>The quantification of acidity or the amount of free acid
present in a substance as determined by alkaline
neutralization.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>valor ácido</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acidification</DESCRIPTOR>
 <DF>To lower the pH of a substance or material to
below 7.0</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>acidificación</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acidolysis</DESCRIPTOR>
 <DF>Chemical decomposition resulting from the addition of an
acid to a compound.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>acidólisis</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acidosis</DESCRIPTOR>
 <DF>A pathologic condition of acid accumulation or depletion of
base in the body. The two main types are respiratory
acidosis and metabolic acidosis, due to metabolic acid
build up.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>acidosis</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acidulants</DESCRIPTOR>
 <DF>An additive added to a product to increase the
acidity of the product.  Acidulants are often
added to food products to increase tartness.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>acidulantes</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acinar cells</DESCRIPTOR>
 <DF>Any secreting cells lining an acinus of a compound
gland.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>células acinosas</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aconitine</DESCRIPTOR>
 <DF>A C19 norditerpenoid alkaloid (diterpenes) from the root of
Aconitum plants. It activates voltage-gated sodium
channels. It has been used to induce arrhythmias in
experimental animals and it has antiinflammatory and
antineuralgic properties.</DF>
 <DS>Medical Subject Headings 2013</DS>
 <ES>aconitina</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Aconitum cammarum</DESCRIPTOR>
 <DF>Probable interspecific hybrid between Aconitum variegatum x
Aconitum napellus.</DF>
 <DS>GRIN (Germplasm Resources Information Network)</DS>
 <ES>Aconitum cammarum</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acquired immunodeficiency syndrome</DESCRIPTOR>
 <DF>An acquired defect of cellular immunity associated
with infection by the human immunodeficiency virus
( HIV), a CD4-positive T-lymphocyte count under
200 cells/microliter or less than 14% of total
lymphocytes, and increased susceptibility to
opportunistic infections and malignant neoplasms.
Clinical manifestations also include emaciation
(wasting) and dementia. These elements reflect
criteria for AIDS as defined by the CDC in 1993.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>síndrome de inmunodeficiencia adquirida</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acrosome reaction</DESCRIPTOR>
 <DF>Changes that occur to liberate the enzymes of the acrosome
of a sperm (spermatozoa). Acrosome reaction allows the
sperm to penetrate the zona pellucida and enter the ovum
during fertilization.</DF>
 <DS>Medical Subject Headings 2013</DS>
 <ES>reacción acrosómica</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actigraphy</DESCRIPTOR>
 <DF>The measurement and recording of motor activity to assess
rest/activity cycles.</DF>
 <DS>Medical Subject Headings 2013</DS>
 <ES>actigrafía</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actin</DESCRIPTOR>
 <DF>Filamentous proteins that are the main constituent
of the thin filaments of muscle fibers. The
filaments (known also as filamentous or F-actin)
can be dissociated into their globular subunits;
each subunit is composed of a single polypeptide
375 amino acids long. This is known as globular or
G-actin. In conjunction with myosins, actin is
responsible for the contraction and relaxation of
muscle.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>actina</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Actinobacillus equuli</DESCRIPTOR>
 <DF>A species of bacteria that infects horses and pigs.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Actinobacillus equuli</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Actinobacillus lignieresii</DESCRIPTOR>
 <DF>A species of bacteria that infects cattle and sheep.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Actinobacillus lignieresii</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actinomycin D</DESCRIPTOR>
 <DF>A compound composed of a two cyclic peptides attached to a
phenoxazine that is derived from Streptomyces parvullus. It
binds to DNA and inhibits RNA synthesis (transcription),
with chain elongation more sensitive than initiation,
termination, or release. As a result of impaired mRNA
production, protein synthesis also declines after
dactinomycin therapy.</DF>
 <DS>Medical Subject Headings 2011</DS>
 <ES>actinomicina D</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actinorhizae</DESCRIPTOR>
 <DF>Symbiotic nitrogen-fixing organs composed of root tissue
and actinomycete bacteria such as Frankia, which may be
found on trees in the genera Alnus, Casuarina and Elaeagnus.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>actinorhizae</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>action potentials</DESCRIPTOR>
 <DF>Abrupt changes in the membrane potential that sweep along
the cell membrane of excitable cells in response to
excitation stimuli.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>potenciales de acción</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activated sludge</DESCRIPTOR>
 <DF>Sludge that has been aerated and treated with
microorganisms in order to accelerate microbial activity
and the oxidation (decomposition) of organic compounds.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>lodo activado</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>active sites</DESCRIPTOR>
 <DF>Protein or enzyme structural motifs that bind to other
substances and activate the function of the proteins or
enzymes.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>sitios activos</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acute course</DESCRIPTOR>
 <DF>Short and relatively severe progression of
disease.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>curso agudo</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acute exposure</DESCRIPTOR>
 <DF>Contact made between a chemical, physical or biological
agent and an organism for a short period of time (typically
less than a day).</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>exposición aguda</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acute phase proteins</DESCRIPTOR>
 <DF>Proteins that are secreted into the blood in
increased or decreased quantities by hepatocytes
in response to trauma, inflammation, or disease.
These proteins can serve as inhibitors or
mediators of the inflammatory processes. Certain
acute-phase proteins have been used to diagnose
and follow the course of diseases or as tumor
markers.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>proteínas de fase aguda</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acute toxic class method</DESCRIPTOR>
 <DF>An alternative to the LD-50 test which uses fewer animals
and classifies chemicals as very toxic, toxic, harmful or
unclassified.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>método de clase tóxica aguda</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acute toxicity</DESCRIPTOR>
 <DF>Immediate or short-term adverse reaction of an organism to
a single exposure to a chemical substance.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>toxicidad aguda</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ad valorem duty</DESCRIPTOR>
 <DF>Tariff defined as a percentage of the value of an imported
commodity or product.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>derecho ad valorem</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adaptive radiation</DESCRIPTOR>
 <DF>Rapid divergent evolution of a more generalized
ancestral species into a variety of more
specialized species or subspecies which fill
unoccupied ecological niches.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>radiación adaptativa</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>additive effect</DESCRIPTOR>
 <DF>A biologic response to exposure to multiple substances that
equals the sum of responses of all the individual
substances added together.</DF>
 <DS>Agency for Toxic Substances and Disease Registry, Centers
for Disease Control and Prevention</DS>
 <ES>efecto aditivo</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>additive gene effects</DESCRIPTOR>
 <DF>Gene action which is the result of genes acting
independently of genetic background so that each
gene has an equal ability to be expressed and
makes an independent contribution to the
expression of the trait.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>efectos genéticos aditivos</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>additives</DESCRIPTOR>
 <DF>Substances added to a product, usually in small quantities,
in order to alter its characteristics or quality.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>aditivos</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Adequate Intakes</DESCRIPTOR>
 <DF>When sufficient scientific evidence is not
available to estimate an average requirement,
Adequate Intakes are set.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Ingestas Adecuadas</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adhesins</DESCRIPTOR>
 <DF>Cell-surface components or appendages of bacteria
that facilitate adhesion to other cells or to
inanimate surfaces. Most fimbriae of gram-negative
bacteria function as adhesins, but in many cases
it is a minor subunit protein at the tip of the
fimbriae that is the actual adhesin. In
gram-positive bacteria, a protein or
polysaccharide surface layer serves as the
specific adhesin.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>adhesinas</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adhesives</DESCRIPTOR>
 <DF>A substance capable of holding materials together by
surface attachment.  It is a general term and includes
cements, mucilage, and paste, as well as glue.</DF>
 <DS>Forest Products Laboratory. 2010. Wood handbook - Wood as
an engineering material. Gen. Tech. Rep. FPL-GTR-190.
Madison, WI: U.S. Department of Agriculture, Forest
Service, Forest Products Laboratory</DS>
 <ES>adhesivos</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adipokines</DESCRIPTOR>
 <DF>Polypeptides produced by the adipocytes. They include
leptin, adiponectin, resistin, and many cytokines of the
immune system, such as tumor necrosis factor-alpha,
interleukin-6, and complement factor D (also known as
adipsin). They have potent autocrine, paracrine, and
endocrine functions.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>adipocinas</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adipokinetic hormone</DESCRIPTOR>
 <DF>Peptide hormones produced by some insect species
stimulating the release of acylglycerols from the
fat body which are used as an energy source by the
flight muscles. There are several types of
peptides with adipokinetic activity.  These
peptides are composed of 8-10 amino acids.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>hormona adipocinética</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adiponectin</DESCRIPTOR>
 <DF>A 30-kDa complement C1Q-related protein, the most abundant
gene product secreted by fat cells of the white adipose
tissue. Adiponectin modulates several physiological
processes, such as metabolism of glucose and fatty acids,
and immune responses. Decreased plasma adiponectin levels
are associated with insulin resistance, type 2 diabetes
mellitus, obesity and atherosclerosis.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>adiponectina</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adiposity</DESCRIPTOR>
 <DF>The amount of fat or lipid deposit at a site or an organ in
the body, an indicator of body fat status.</DF>
 <DS>Medical Subject Headings 2013</DS>
 <ES>adiposidad</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Adirondacks</DESCRIPTOR>
 <DF>An area around the Adirondack Mountains located in northern
New York State and sometimes included as part of the
Appalachian region.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Adirondacks</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adjuvants</DESCRIPTOR>
 <DF>An ingredient that improves the properties of a
drug, vaccine or pesticide formulation.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>adyuvantes</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administered dose</DESCRIPTOR>
 <DF>The amount of a substance given to a test subject (human or
animal) to determine dose-response relationships.</DF>
 <DS>US Environmental Protection Agency</DS>
 <ES>dosis administrada</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administration of justice</DESCRIPTOR>
 <DF>The practical execution of the law, including law
enforcement, corrections and the judicial system.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>administración de justicia</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adolescent fathers</DESCRIPTOR>
 <DF>Males between the ages of 12-18 who have fathered
children.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>padres adolescentes</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adsorbents</DESCRIPTOR>
 <DF>A substance which has the property of attaching or
accumulating another substance on its surface.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>adsorbentes</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adsorption</DESCRIPTOR>
 <DF>The taking up of one substance onto the surface of
another.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>adsorción</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult literacy</DESCRIPTOR>
 <DF>The ability of adults (ages 18 and older) to read
and write.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>alfabetización de adultos</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adulterated products</DESCRIPTOR>
 <DF>Products containing any deleterious substance rendering it
injurious to health or products produced using ingredients
or processes that are inconsistent with their labels.  See
Federal Food, Drug and Cosmetic Act Section 402 [21 U.S.C.
342].</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>productos adulterados</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adulticides</DESCRIPTOR>
 <DF>Chemical agents that kill the adult stage of a
pest or parasite.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>adulticidas</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>advocacy</DESCRIPTOR>
 <DF>Active support in favor of an idea, policy,
individual, group or cause.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>apoyo</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Aegilotriticum</DESCRIPTOR>
 <DF>Intergeneric hybrid of Aegilops x Triticum.</DF>
 <DS>Germplasm Resources Information Network</DS>
 <ES>Aegilotriticum</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aerobic digestion</DESCRIPTOR>
 <DF>A biochemical process which uses microorganisms in
the presence of oxygen to decompose organic matter.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>digestión aeróbica</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aerodynamics</DESCRIPTOR>
 <DF>The study of the flow of gases (especially air)
and the forces that affect objects in motion;
specifically, the interaction of moving objects
with the atmosphere.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>aerodinámica</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Aesculus carnea</DESCRIPTOR>
 <DF>Interspecific hybrid between Aesculus hippocastanum x
Aesculus pavia.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Aesculus carnea</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>affordability</DESCRIPTOR>
 <DF>Being able to bear the cost or to have the
financial means for purchasing goods or services.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>solvencia</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>African horse sickness</DESCRIPTOR>
 <DF>An insect-borne reovirus infection of horses,
mules and donkeys in Africa and the Middle East;
characterized by pulmonary edema, cardiac
involvement, and edema of the head and neck.</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>enfermedad del caballo africano</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>African horse sickness virus</DESCRIPTOR>
 <DF>A species of Orbivirus that causes disease in horses,
mules, and
donkeys and can also infect other animals such as dogs,
cattle,
sheep, goats and humans. The virus is transmitted by
blood-sucking (hematophagous) insects - usually biting
midges of
the genus Culicoides.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>African horse sickness virus</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>African swine fever</DESCRIPTOR>
 <DF>A sometimes fatal Asfivirus infection of pigs,
characterized by fever, cough, diarrhea, hemorrhagic lymph
nodes, and edema of the gallbladder. It is transmitted
between domestic swine by direct contact, ingestion of
infected meat, or fomites, or mechanically by biting flies
or soft ticks (genus Ornithodoros).</DF>
 <DS>Medical Subject Headings 2012</DS>
 <ES>fiebre porcina africana</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>African swine fever virus</DESCRIPTOR>
 <DF>A sometimes fatal Asfivirus infection of pigs,
characterized by fever, cough, diarrhea, hemorrhagic lymph
nodes, and edema of the gallbladder. It is transmitted
between domestic swine by direct contact, ingestion of
infected meat, or fomites, or mechanically by biting flies
or soft ticks (genus Ornithodoros).</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>African swine fever virus</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>after-ripening</DESCRIPTOR>
 <DF>The dormancy period following seed formation,
necessary for embryo changes that insure
germination.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>postmaduración</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agarose</DESCRIPTOR>
 <DF>A polysaccharide present in agar and responsible
for its gelling.  It consists of residues of
3,6-anhydo-L-galactose and D-galactose.  It is
used as a medium for gel chromatography.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>agarosa</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agglomeration economies</DESCRIPTOR>
 <DF>The benefits obtained when multiple companies are located
near each other, due to decreased production costs and
other advantages brought by network effects.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>economías de aglomeración</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aggregate exposure</DESCRIPTOR>
 <DF>The sum total of all exposure to a specific biological,
chemical or physical agent via relevant routes, pathways
and sources.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>exposicón agregada</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agonistic behavior</DESCRIPTOR>
 <DF>Agressive or defensive social behavior such as
fighting, fleeing or submitting between
individuals usually of the same species.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>conducta agonista</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Agricultural Adjustment Act of 1933</DESCRIPTOR>
 <DF>Signed May 12, 1933, this law introduced the price
support programs, including production
adjustments, and the incorporation of the
Commodity Credit Corporation (CCC), under the laws
of the State of Delaware on October 17, 1933.  The
program benefits were financed mostly by
processing taxes on the specific commodity.  The
Act also made price support loans by the CCC
mandatory for the designated &quot;basic&quot; (storable)
commodities: corn, wheat, and cotton.  Support for
other commodities was authorized upon the
recommendation by the Secretary of Agriculture
with the President&apos;s approval.</DF>
 <DS>Agriculture Fact Book, USDA</DS>
 <ES>Ley de Ajuste Agrícola de 1933</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Agricultural Agreement</DESCRIPTOR>
 <DF>The agreement within the World Trade Organization that
commits members to improving market access and reducing
subsidies which distort trade in agriculture, starting with
tariffication.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>Acuerdo Agrícola</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural biotechnology</DESCRIPTOR>
 <DF>The use of living organisms, cells or cell constituents for
the purpose of developing agricultural products or
improving livestock or crop plants.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>biotecnología agrícola</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural colleges</DESCRIPTOR>
 <DF>Educational institutions offering a curriculum in
agricultural sciences.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>universidades agrícolas</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural engineering</DESCRIPTOR>
 <DF>Discipline which includes the design of machinery,
equipment and structures used for agricultural operations
and
the storage and processing of agricultural
commodities.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>ingeniería agrícola</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural experiment stations</DESCRIPTOR>
 <DF>Centers where scientific research is conducted in order to
improve food and agricultural production. Experiment
station scientists and staff work with farmers and other
members of the agriculture and food industry.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>estaciones agrícolas experimentales</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural health and safety</DESCRIPTOR>
 <DF>The promotion of a safe and healthy environment to support
the physical and mental well-being among humans engaged in
agricultural activities.</DF>
 <DS>NAL Thesaurus Staff</DS>
 <ES>salud y seguridad de la agricultura</ES>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agroecological zones</DESCRIPTOR>
 <DF>Land areas classified by their biophysical
attributes, (such as rainfed soil moisture
availability, temperature, length of growing
period), in order to cluster land use types into
homogenous units for agricultural production
considerations.</DF>
 <DS>NAL Thesaurus Staff</DS>